services:
  - type: web
    name: bitespeed
    env: node
    plan: free
    buildCommand: npm config set production false && npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: build
